### ISSUE TITLE
If I use "?", the editor write "<>"

### ISSUE THREAD

**Issue by Gynidark** [tovic/markdown-text-editor#4]
Hello,

If I use "?", the editor write "<>"

it's possible to find a solution for resolve this bug

Thanks, Gynidark

**Comment by tovic** [comment]
Are you using **Mac**?

**Comment by Gynidark** [comment]
No, **Ubuntu 15.04**

**Comment by Gynidark** [comment]
Even on the demo, i have this marigold :(

**Comment by tovic** [comment]
Could you give me the console message when you are typing from your OS. This is mine, from Firefox in Windows computer:

![2015-10-20_110648](https://cloud.githubusercontent.com/assets/1669261/10597633/c93a4188-771a-11e5-85f3-a0ac420e8160.png)

~~~
16 → shift
191 → ?
16 → shift
188 → <
~~~

**Comment by Gynidark** [comment]
![](https://sc-cdn.scaleengine.net/i/15ee96615fcfcd0c31ba265edd8176ab.png)

**16** shift
**188** <>

**Comment by tovic** [comment]
So the keycode is correct but the keyboard symbol isn&rsquo;t. If you do the same thing in plain _textarea_ and produce the correct results, this means that there is a problem specific to the OS. I&rsquo;ll try to find out the solution.

**Comment by Gynidark** [comment]
That just your editor , not my OS , everything works except my inputs in the editor. :/ Thank you

**Comment by rizqyhi** [comment]
Its working just fine. I'm using **Chrome** on **Ubuntu 14.04**.
